# Generated by Django 4.1 on 2023-07-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensaje", models.CharField(max_length=500)),
                ("prioridad", models.PositiveSmallIntegerField()),
                ("pto", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
