# Generated by Django 4.1 on 2023-07-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_solicitud", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitud",
            name="mensaje",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name="solicitud",
            table="solicitud_table",
        ),
    ]
