# Generated by Django 4.1 on 2023-07-07 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_solicitud", "0003_solicitud_actualizado_solicitud_hora"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="solicitud",
            table="db.sqlite3",
        ),
    ]
