# Generated by Django 4.1 on 2023-07-07 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_solicitud", "0004_alter_solicitud_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="solicitud",
            table="solicitud_table",
        ),
    ]
