# Generated by Django 4.1 on 2023-07-12 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_solicitud", "0005_alter_solicitud_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="solicitud",
            old_name="hora",
            new_name="creado",
        ),
    ]
